name: Build WASM Core

on:
  push:
    paths:
      - 'bration-extinction-core/**'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build WASM package
        working-directory: ./bration-extinction-core
        run: wasm-pack build --target web --release

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: bration-extinction-wasm
          path: bration-extinction-core/pkg/
